### ISSUE TITLE
pls add cron job for auto update.

### ISSUE THREAD

**Issue by SamYuan1990** [SQRPI/ArkOneGraph#2]
ref to https://www.cyberciti.biz/faq/how-do-i-add-jobs-to-cron-under-linux-or-unix-oses/

“0 0 * * *”. python main.py
“0 * * * *”. python main.py

Run once a week, “0 0 * * 0”.
--
hope able to add cron job on server so that able to update in automatic way.

**Comment by SQRPI** [comment]
ty, auto update has been deployed
